name: torganic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.3.1 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter



  #Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5


  # Icons
  cupertino_icons: ^1.0.6


  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/
    - assets/icons/

  # Local Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         styles: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
